Use `Email` instead of the `RawMessage` type
freshheads/FHMailerBundle pull request #6
Opened 2019-11-14 15:34 UTC by mishaklomp

2019-11-14 15:54 UTC, fruitwasp approved these changes

2019-11-14 22:43 UTC, jvandesande requested changes

2019-11-14 22:43 UTC, jvandesande commented on src/Composer/TemplatedEmailComposer.php
> -        if (!$message instanceof TemplatedEmail) {
Deze check moet wel blijven. Want op een `Email` instance kun je geen templates setten

2019-11-15 15:46 UTC, jvandesande approved these changes

2019-11-18 09:08 UTC, merged